// Automatically generated by Simulation Framework ICD utility. DO NOT MODIFY!
// This area refers to ICD [ICD for RC27J] (ver: 1)
// Memory Area Name: TXT_INPUT_DATA (ver: 12) 
// Total size of this area is: 160 bytes.
#ifndef TXT_UPLINK_DATA_DEF
#define TXT_UPLINK_DATA_DEF


#include <stdint.h>


#ifndef __cplusplus
#ifndef bool
#define bool uint32_t
#endif
#endif

#define TXT_INPUT_DATA_VERSION 12

#if defined (_MSC_VER) || defined (__MINGW32__)
#define __attribute__(x)
#pragma pack(push)
#pragma pack(1)
#endif



typedef struct __attribute__((packed)) // This struct will be repeated 1 times in memory
{
    int32_t TIME_STAMP_DATA_YEAR;
    int32_t TIME_STAMP_DATA_MONTH;
    int32_t TIME_STAMP_DATA_DAY;
    int32_t TIME_STAMP_DATA_SECOND;
    int32_t TIME_STAMP_DATA_MINUTE;
    int32_t TIME_STAMP_DATA_HOUR;
    
    int32_t ADS_GROUND_PDU;
    int32_t ADS_CANCEL_CONTRACT;
    int32_t ADS_CONTRACT_REQUEST_CONTRACT_TYPE;
    int32_t ADS_CONTRACT_REQUEST_INTEGRITY_CHK_LENGTH;
    char ADS_CONTRACT_REQUEST_INTEGRITY_CHK[ADS_CONTRACT_REQUEST_INTEGRITY_CHK_LENGTH];
    int32_t ADS_PERIODIC_REQUEST_CONTRACT_NUM;
    int32_t ADS_PERIODIC_REQUEST_REPORTING_RATE;
    int32_t ADS_PERIODIC_REQUEST_AIR_IDENTIFICATION;
    int32_t ADS_PERIODIC_REQUEST_PROJECT_PROFILE;
    int32_t ADS_PERIODIC_REQUEST_MET_INFO;
    int32_t ADS_PERIODIC_REQUEST_EXT_PROFILE_MODULE;
    int32_t ADS_PERIODIC_REQUEST_ETA_MIN_MAX_MODULE;
    int32_t ADS_PERIODIC_REQUEST_EXT_PROFILE_EPP_NUM_OF_WAY;
    int32_t ADS_PERIODIC_REQUEST_ETA_MIN_MAX_FIX_LENGTH;
    char ADS_PERIODIC_REQUEST_ETA_MIN_MAX_FIX[ADS_PERIODIC_REQUEST_ETA_MIN_MAX_FIX_LENGTH];

} TXT_ADS_GROUND;


// Total size is: 160

#if defined (_MSC_VER) || defined (__MINGW32__)
#pragma pack(pop)
#endif

#endif
